### ISSUE TITLE
Extract composite packages - multiple bulk import

### ISSUE THREAD

**Issue by thetawave** [VenoMKO/RealEditor#1]
When updating Event Basebody diff + norm with a composite package, Real Editor does not allow importing both. You can only do diff, or norm. Then you will manually have to update >60 gpks with diff or norm, whichever was not done in the bulk import. It would be great if bulk import could do both diff and norm at the same time.

**Comment by VenoMKO** [comment]
This feature is coming soon. Right now, you can use a workaround:

1. Use bulk import to import a diffuse texture
2. Add all gpks with a custom diffuse texture to the TMM
3. Restart RE
4. Import normal, specular, or whatever as you would normally do
