### ISSUE TITLE
Velika does not import into UE 4.27 :o

### ISSUE THREAD

**Issue by Kleinstadtkatze** [VenoMKO/RealEditor#10]
Above- i followed the instructions but I end up without any meshes loading after I import the actors. I am probably just too dumb for that, i am just an artist :D  but i wanted to ask if anyone could send me the Velika UE Project. I want to retexture Velika for a personal and university project and upload that textures once they are finished :)

**Comment by VenoMKO** [comment]
Most likely you imported static meshes incorrectly. Make sure you copied the `S1Game` folder from `StaticMeshes` to the UE's `Contents`.
As for the UE Project, the game's license does not allow this, so it can't be shared here.
