### ISSUE TITLE
Question: How to join head and body

### ISSUE THREAD

**Issue by RabberDakk** [VenoMKO/RealEditor#11]
This is not a bug report. Currently, I'm using RealEditor to extract the model and apply animations, but I'm having problem merging the `[Body,Hand,Leg]` and `[Hair]` and `[Face]` and `[Tail]` position data. Applying animation causes minor misalignment.

<img src="https://user-images.githubusercontent.com/59415461/159165760-bf6439f6-417d-42e0-9de1-28e4aca1458d.png" width="300px">

The bone that joins `[Hair]` and `[Face]` does not appear to exist in `[Body]`. As a workaround, I'm trying to adjust the position by making it a child of a Bone that looks like it, but it does not work...

<img src="https://user-images.githubusercontent.com/59415461/159165953-88fb87c6-9f71-4511-b295-64936c90fc32.png" width="400px">

May I ask for your advice on this matter?

#### Files

- Popori_F_H.Skel.15.Popori_F_H15_Body_Skel
- Popori_F_H.Skel.15.Popori_F_H15_Hand_Skel
- Popori_F_H.Skel.15.Popori_F_H15_Leg_Skel
- Popori_F_Head.Skel.00.PoPori_F_face00_skel
- Popori_F_Head.Skel.00.Popori_F_Hair00B_Skel
- Popori_F_Head.Skel.00.Popori_F_Tail00_Skel
- Popori_F_ANI.Anim.Popori_F_Share_Anim_Level3I
- Popori_F_Face_ANI.Anim.Popori_F_Share_Face_Anim_Level3I
- Popori_F_Tail_ANI.Anim.00.Popori_F_Share_Tail00_Anim_Level3I
- Popori_F_Hair_ANI.Anim.01.Popori_F_Share_Hair01_Anim_Level3I

----

Thank you very much for powerful tool. When I opened the map in RealEditor I was so impressed that I couldn't help but squeal.

**Comment by VenoMKO** [comment]
I never tried to assemble meshes myself, but as far as I know, mesh attachments have different offsets.
You should be able to find them in the `DataCeneter_Final.dat`.
To unpack and decrypt the file, you can use RE's built-in DataCenter Tool([Guide](https://github.com/VenoMKO/RealEditor/wiki/Export-DataCenter.dat-as-XML-or-JSON)).

**Comment by RabberDakk** [comment]
Thanks for the advice on the location of the offset data. I'll look for it 🙏
