### ISSUE TITLE
How to find PG models

### ISSUE THREAD

**Issue by Imperyalis** [VenoMKO/RealEditor#12]
Hi, this isn't an issue. But, I really wanted to get the models of my PGs. Do someone know where exactly are they stored?

**Comment by VenoMKO** [comment]
What's PG?

**Comment by Imperyalis** [comment]
Player character

**Comment by VenoMKO** [comment]
All character parts can be found in: `Client\S1Game\CookedPC\Art_Data\Packages\CH\PC`

**Comment by Imperyalis** [comment]
Is there any way to export more than one file at the time? and to search with filters or words inside the package files?

**Comment by VenoMKO** [comment]
No. You need to open each file and select what exactly you want to export from it.
To search across all packages, you can decrypt the `Client\S1Game\CookedPC\CompositePackageMapper.dat` file and use any text editor.

**Comment by Imperyalis** [comment]
I see. Thanks

**Comment by Imperyalis** [comment]
Another question: Where are the tails?
When I look for Popori's (and Popori F (aka Elins)) tails the only thing I'm able to find is the animation pkg. Trying to export the animation files the software don't find any rig, so I can't export. Also, with some shared animations the program crashes.
