### ISSUE TITLE
Export part of a composite package as a package?

### ISSUE THREAD

**Issue by houthakker888** [VenoMKO/RealEditor#13]
I'm trying to edit animations somehow, and I figured maybe I could run them through UDK, get animsequence files, then use UPKRepack. I'll have to unpack the source packages, so I wonder how, or if I can do it? So far I can only export individual files.

I don't have much knowledge about Tera or UE3 in general, so if what I'm planning to do won't work at all, that'll be good to know as well.

**Comment by VenoMKO** [comment]
This won't work.
