### ISSUE TITLE
64bit GPK edits

### ISSUE THREAD

**Issue by KYGAS** [VenoMKO/RealEditor#15]
Hello,

I wanted to make some GPK edits on the 64bit client ( specifically p100.02 GF )
However the Ctrl+S option doesn't seem to work and I have issues figuring out how to save/what to save where..

Could you provide a small guide for changing 64bit GPKs and seeing the change in the client?

Thank you

**Comment by VenoMKO** [comment]
You can find all guides in the [Wiki](https://github.com/VenoMKO/RealEditor/wiki)
Guides related to your question:
1. [How to create a texture mod](https://github.com/VenoMKO/RealEditor/wiki/Create-a-composite-mod)
2. [How to install a mod](https://github.com/VenoMKO/TMM/wiki/Add-mods)
