### ISSUE TITLE
Noob question about importing into 3dsmax, mesh and texture

### ISSUE THREAD

**Issue by AciesGecko** [VenoMKO/RealEditor#16]
Hello, I'm very new to 3dsmax and importing models, I have two problems I can't solve on my own, and I looked through the wiki and couldn't find an answer.
First is,  mesh related. I export a model with Real Editor and I get a .fbx file. I import to 3dsmax but it gives me a single mesh (body and outfit together) is there a way to separate the meshes? other importers for games separate the parts, if I split the outfit from the body then the skeleton doesn't work anymore. 
Second is how to load the textures, I tried tga, dds and png but 3dsmax doesn't open them, I get a grey mesh. I don't know how to solve this either so I can't understand where does each texture go. 
I hope someone can help !

**Comment by VenoMKO** [comment]
1. This is the way data is stored in GPK files. Ask 3dsmax community how to transfer skin weights.
2. Ask 3dsmax community how to use diffuse maps
