### ISSUE TITLE
RealEditor closes

### ISSUE THREAD

**Issue by WollieWoltaz** [VenoMKO/RealEditor#2]
Hey VenoMKO,

RealEditor is closing automaticly when I try to load any .gpk file.
It says; "Loading Core.u" and then the editor closes.
What does this mean and how can I fix this?

Is it because i have Intel core i9 instead of Haswell or something?

Regards,

**Comment by VenoMKO** [comment]
Hi!
I need more details on this:
* Tera region
* RE version
* OS version

If you are using the latest RE version have you tried any earlier version(e.g., 2.11)?

**Comment by WollieWoltaz** [comment]
I didn't installed Tera online yet, I extracted the files via SteamDepot. I wanted to check first if I could open the files before downloading this huge game. So I guess the region is just Europe, The Netherlands.

RE version: 2.13
OS version: Windows 10 home, 64-bit

**Comment by VenoMKO** [comment]
> I didn't installed Tera online yet

This might be the issue. RE depends on Tera's system files(e.g., Core, Engine, S1Game, etc...) and won't work if any of the files are incomplete or missing.

Also, if you have an antivirus, you can try to add RE to its white-list. I've seen a few cases where an antivirus(e.g., Avast) killed the RE process.

Let me know if you have any changes with the issue.

**Comment by VenoMKO** [comment]
I've just checked, RE crashes without any error message if a `Core.u` file is 0kb. I guess you'll need to download the full game.

**Comment by WollieWoltaz** [comment]
Okay thanks for checking. At least I know now what the issue is.
Thanks again.
