### ISSUE TITLE
Monster skeletal meshes/anims location

### ISSUE THREAD

**Issue by WollieWoltaz** [VenoMKO/RealEditor#3]
Hello again,

I installed Tera again last night, and the latest version of RealEditor seems to work fine now but like the topic says, were are all the monster skeletal meshes and animations located? In wich .gpk files should I look?
Also are the monsters located in the same .gpk file or are they spread over several packages?

Regards,

**Comment by WollieWoltaz** [comment]
Got it now. I also didn't noticed there was a "source" button. This one is verry helpfull!
Btw.. is there a way to open multiple .gpk files?

**Comment by VenoMKO** [comment]
As far as I remember you have Steam version of the game.  If that's the case, close RE and start the game. The game's launcher will download additional data and update the client. Then, close the game and start RE. It should find all the downloaded data and show the **Source** button if possible. If not, let me know which object in what GPK does not have the button.

As for the multiple files - Yes. You can open as many files as you want by using the **File** menu or by double-clicking GPK files in the explorer.

**Comment by WollieWoltaz** [comment]
I'm sorry i wasn't clear enough.. I meant to say that "I do have the source button available". I just didn't noticed it beforehand.

But if I open multiple .gpk files it'll also open multiple tabs. I was more talking about selecting multiple .gpk's and open them in 1 tab..

**Comment by VenoMKO** [comment]
Not quite sure if I got you right about tabs stuff. Each RE window represents a unique GPK file, so you can't open multiple GPKs in a single window. When you press the **Source** button, RE finds a GPK with the selected object and opens it. If you want to export GPKs in bulk without the **Source** hassle, you can use this guide: [Bulk Export](https://github.com/VenoMKO/RealEditor/wiki/Export-a-GPK-or-GMP). It may not work for some animations tho.

**Comment by WollieWoltaz** [comment]
RE windows I meant indeed and thanks for the clarrification. And i'll take a look at the Bulk export option.
