### ISSUE TITLE
Imported FBX animation doesn't have some parts attached

### ISSUE THREAD

**Issue by Triadasoul** [VenoMKO/RealEditor#7]
![2021-11-08_10-54-39](https://user-images.githubusercontent.com/15606837/140688674-d1a1f787-f9b6-4bf7-9e41-ba744fba7691.png)
![изображение](https://user-images.githubusercontent.com/15606837/140688744-1a99e960-1696-4cbd-888c-392e817adf49.png)

Imported FBX animation doesn't have some parts attached (Larvaking from Monsters folder)

**Comment by VenoMKO** [comment]
That's Blender's FBX plugin issue. Ask Blender community how to fix this.
Microsoft 3D Viewer, Autodesk FBX Review, and Autodesk Maya 2022 work correctly:
![screenshot](https://i.gyazo.com/1947074dbe7bf404065d99e175ff3c56.png)

**Comment by Triadasoul** [comment]
I tried to open it in 3d viewer - its still separated 
![изображение](https://user-images.githubusercontent.com/15606837/140691411-cb31f07b-59e3-4414-9fa6-ef74d0d314ce.png)

**Comment by VenoMKO** [comment]
Looks like a bug. Use RE v.2.31 as a temporary solution.

**Comment by Triadasoul** [comment]
![изображение](https://user-images.githubusercontent.com/15606837/140693165-a0ba70b0-c2f5-4d08-be43-687babe5fe99.png)

2.31 works! ) Thank you!
And thank you for the great tool!

**Comment by VenoMKO** [comment]
Fixed in **v.2.35**
