### ISSUE TITLE
Failed to open Package

### ISSUE THREAD

**Issue by CelestCSilvari** [VenoMKO/RealEditor#8]
Hello, I don't know if this is an issue or if im just being stupid, but sometimes real editor wont let me go to the source of a model and sometimes i just xant click on it,
I want the model files from Tera online and i cant get the shurikens or dual swords from event 25 the christmas skins i can get the textures but nothing els
![Untitled](https://user-images.githubusercontent.com/96462466/146880743-d644afb4-7611-4e50-b492-3244ae9e1f4c.png)
e

**Comment by VenoMKO** [comment]
Hi. Open your `D:\Games\tera\Client\S1Game\CookedPC` folder and check if the file `2073cbd3_69.gpk` exists. Its size should be roughly 130Mb.

**Comment by CelestCSilvari** [comment]
> Hi. Open your `D:\Games\tera\Client\S1Game\CookedPC` folder and check if the file `2073cbd3_69.gpk` exists. Its size should be roughly 130Mb.

It was but it was a blaster from i think the pink Pink Heart weapon set

**Comment by CelestCSilvari** [comment]
I finally got it work
I just needed to repair the game im sorry to have bothered you
