### ISSUE TITLE
[BNS]UE3 Support

### ISSUE THREAD

**Issue by LievreAI** [VenoMKO/RealEditor#9]
hello dear @VenoMKO 
can you support the blade & soul game
not the ue4 version but the ue3 version?
if you will need a client i can bring you it since official bns
already have moved on to ue4 i want the maps of the ue3 version
i will really appriciate if you can support it

**Comment by VenoMKO** [comment]
Hi! Unfortunately, I don't have time for BNS. I've made a separate branch with BNS support, but it's far from perfect and does not support maps. As far as I remember there were issues with physics and collisions that made RE crash. You can use this branch as a starting point to improve BNS support.

Branch: https://github.com/VenoMKO/RealEditor/tree/bns
